openapi: 3.0.3
info:
    title: Epup Index Creator
    version: 0.0.1
servers:
    - url: http://localhost:8000
paths:
    /books:
        get:
            tags:
                - epub_index_creator
            summary: ListBooks epub_index_creator
            operationId: epub_index_creator#ListBooks
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ListBooksRequestBody'
                        example:
                            limit: 52
                            offset: 8387359067837253274
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Book'
                                example:
                                    - author: Est ut.
                                      isbn: Incidunt adipisci consectetur consequatur repudiandae.
                                      language: Aspernatur velit dolores aperiam adipisci qui.
                                      pages:
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                      publisher: Ut veniam est aut occaecati odio corrupti.
                                      title: Est eligendi sit velit quo reiciendis.
                                    - author: Est ut.
                                      isbn: Incidunt adipisci consectetur consequatur repudiandae.
                                      language: Aspernatur velit dolores aperiam adipisci qui.
                                      pages:
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                      publisher: Ut veniam est aut occaecati odio corrupti.
                                      title: Est eligendi sit velit quo reiciendis.
                                    - author: Est ut.
                                      isbn: Incidunt adipisci consectetur consequatur repudiandae.
                                      language: Aspernatur velit dolores aperiam adipisci qui.
                                      pages:
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                      publisher: Ut veniam est aut occaecati odio corrupti.
                                      title: Est eligendi sit velit quo reiciendis.
                                    - author: Est ut.
                                      isbn: Incidunt adipisci consectetur consequatur repudiandae.
                                      language: Aspernatur velit dolores aperiam adipisci qui.
                                      pages:
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                        - keywords:
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                            - keyword: Unde recusandae saepe velit ullam omnis.
                                          title: Sint sint repellat sapiente porro.
                                      publisher: Ut veniam est aut occaecati odio corrupti.
                                      title: Est eligendi sit velit quo reiciendis.
                            example:
                                - author: Est ut.
                                  isbn: Incidunt adipisci consectetur consequatur repudiandae.
                                  language: Aspernatur velit dolores aperiam adipisci qui.
                                  pages:
                                    - keywords:
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                      title: Sint sint repellat sapiente porro.
                                    - keywords:
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                      title: Sint sint repellat sapiente porro.
                                  publisher: Ut veniam est aut occaecati odio corrupti.
                                  title: Est eligendi sit velit quo reiciendis.
                                - author: Est ut.
                                  isbn: Incidunt adipisci consectetur consequatur repudiandae.
                                  language: Aspernatur velit dolores aperiam adipisci qui.
                                  pages:
                                    - keywords:
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                      title: Sint sint repellat sapiente porro.
                                    - keywords:
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                        - keyword: Unde recusandae saepe velit ullam omnis.
                                      title: Sint sint repellat sapiente porro.
                                  publisher: Ut veniam est aut occaecati odio corrupti.
                                  title: Est eligendi sit velit quo reiciendis.
        post:
            tags:
                - epub_index_creator
            summary: CreateBook epub_index_creator
            operationId: epub_index_creator#CreateBook
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Book'
                        example:
                            author: Ut cumque non consequatur fuga voluptas.
                            isbn: Molestiae veniam veritatis est sit error voluptatum.
                            language: Dolorem et iste sit quia.
                            pages:
                                - keywords:
                                    - keyword: Tenetur iusto animi mollitia eius magni.
                                    - keyword: Tenetur iusto animi mollitia eius magni.
                                  title: Assumenda est ex asperiores aspernatur enim mollitia.
                                - keywords:
                                    - keyword: Tenetur iusto animi mollitia eius magni.
                                    - keyword: Tenetur iusto animi mollitia eius magni.
                                  title: Assumenda est ex asperiores aspernatur enim mollitia.
                            publisher: Ratione quidem nam.
                            title: Nihil harum quia consequatur voluptates maiores.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Aspernatur sint quam nemo eaque aut.
                                isbn: Ducimus omnis qui necessitatibus natus voluptatum voluptatem.
                                language: Exercitationem placeat ad.
                                pages:
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                publisher: Eos temporibus itaque nostrum magni.
                                title: Ex dignissimos sed qui et.
    /books/{isbn}:
        delete:
            tags:
                - epub_index_creator
            summary: DeleteBook epub_index_creator
            operationId: epub_index_creator#DeleteBook
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  schema:
                    type: string
                    description: ISBN of the book
                    example: Sed in.
                  example: Omnis recusandae consequatur ut cupiditate et.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteBookRequestBody'
                        example:
                            book:
                                author: Sunt qui nisi ut et dolor et.
                                isbn: Sed explicabo quibusdam.
                                language: Est eveniet aspernatur beatae eum et nihil.
                                pages:
                                    - keywords:
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                      title: Assumenda est ex asperiores aspernatur enim mollitia.
                                    - keywords:
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                      title: Assumenda est ex asperiores aspernatur enim mollitia.
                                    - keywords:
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                      title: Assumenda est ex asperiores aspernatur enim mollitia.
                                    - keywords:
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                        - keyword: Tenetur iusto animi mollitia eius magni.
                                      title: Assumenda est ex asperiores aspernatur enim mollitia.
                                publisher: Non id cum nemo voluptas illum.
                                title: Odit aliquam nihil aliquid.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - epub_index_creator
            summary: FindBook epub_index_creator
            operationId: epub_index_creator#FindBook
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  schema:
                    type: string
                    description: ISBN of the book
                    example: Nulla sunt soluta quis.
                  example: Quia ex ut perferendis in magni.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Esse in cupiditate sunt.
                                isbn: Repudiandae molestias.
                                language: In reiciendis quaerat temporibus.
                                pages:
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                publisher: Et quis.
                                title: Sunt et.
        put:
            tags:
                - epub_index_creator
            summary: UpdateBook epub_index_creator
            operationId: epub_index_creator#UpdateBook
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  schema:
                    type: string
                    description: ISBN of the book
                    example: Deleniti dolorum autem in enim exercitationem eveniet.
                  example: Et distinctio numquam culpa est magnam totam.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateBookRequestBody'
                        example:
                            author: Doloremque totam voluptatibus excepturi.
                            language: Placeat nam omnis esse.
                            publisher: Veniam assumenda quae dolores cum molestiae.
                            title: Modi dolores non ducimus officia saepe.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Book'
                            example:
                                author: Non sit et eum officia doloribus.
                                isbn: Suscipit facilis quasi qui ab.
                                language: Ipsum deserunt incidunt non qui non.
                                pages:
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                    - keywords:
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                        - keyword: Totam omnis qui dolorem perferendis voluptatibus.
                                      title: Ut dicta.
                                publisher: Deserunt eius facere non.
                                title: Magnam voluptatem occaecati possimus non facere.
    /openapi.json:
        get:
            tags:
                - epub_index_creator
            summary: Download ./gen/http/openapi.json
            operationId: epub_index_creator#/openapi.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        Book:
            type: object
            properties:
                author:
                    type: string
                    description: Author of the book
                    example: Qui laborum voluptatibus iste.
                isbn:
                    type: string
                    description: ISBN of the book
                    example: Laborum voluptates magni qui odio neque.
                language:
                    type: string
                    description: Language of the book
                    example: Autem tempore nemo explicabo voluptatem illum provident.
                pages:
                    type: array
                    items:
                        $ref: '#/components/schemas/Page'
                    description: Pages of the book
                    example:
                        - keywords:
                            - keyword: Unde recusandae saepe velit ullam omnis.
                            - keyword: Unde recusandae saepe velit ullam omnis.
                            - keyword: Unde recusandae saepe velit ullam omnis.
                          title: Sint sint repellat sapiente porro.
                        - keywords:
                            - keyword: Unde recusandae saepe velit ullam omnis.
                            - keyword: Unde recusandae saepe velit ullam omnis.
                            - keyword: Unde recusandae saepe velit ullam omnis.
                          title: Sint sint repellat sapiente porro.
                        - keywords:
                            - keyword: Unde recusandae saepe velit ullam omnis.
                            - keyword: Unde recusandae saepe velit ullam omnis.
                            - keyword: Unde recusandae saepe velit ullam omnis.
                          title: Sint sint repellat sapiente porro.
                publisher:
                    type: string
                    description: Publisher of the book
                    example: Explicabo ratione praesentium voluptates.
                title:
                    type: string
                    description: Title of the book
                    example: Cupiditate omnis et animi.
            example:
                author: Debitis qui delectus eum consequatur.
                isbn: Eius fugiat.
                language: Possimus iusto nam.
                pages:
                    - keywords:
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                      title: Sint sint repellat sapiente porro.
                    - keywords:
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                      title: Sint sint repellat sapiente porro.
                publisher: Harum laboriosam.
                title: Voluptatem harum a quae.
            required:
                - isbn
                - title
                - author
                - language
                - publisher
                - pages
        DeleteBookRequestBody:
            type: object
            properties:
                book:
                    $ref: '#/components/schemas/Book'
            example:
                book:
                    author: Sunt qui nisi ut et dolor et.
                    isbn: Sed explicabo quibusdam.
                    language: Est eveniet aspernatur beatae eum et nihil.
                    pages:
                        - keywords:
                            - keyword: Tenetur iusto animi mollitia eius magni.
                            - keyword: Tenetur iusto animi mollitia eius magni.
                          title: Assumenda est ex asperiores aspernatur enim mollitia.
                        - keywords:
                            - keyword: Tenetur iusto animi mollitia eius magni.
                            - keyword: Tenetur iusto animi mollitia eius magni.
                          title: Assumenda est ex asperiores aspernatur enim mollitia.
                        - keywords:
                            - keyword: Tenetur iusto animi mollitia eius magni.
                            - keyword: Tenetur iusto animi mollitia eius magni.
                          title: Assumenda est ex asperiores aspernatur enim mollitia.
                        - keywords:
                            - keyword: Tenetur iusto animi mollitia eius magni.
                            - keyword: Tenetur iusto animi mollitia eius magni.
                          title: Assumenda est ex asperiores aspernatur enim mollitia.
                    publisher: Non id cum nemo voluptas illum.
                    title: Odit aliquam nihil aliquid.
            required:
                - book
        Keyword:
            type: object
            properties:
                keyword:
                    type: string
                    description: Keyword of the page
                    example: Vel est velit illum qui.
            example:
                keyword: Consequatur ducimus voluptatum autem quam.
            required:
                - keyword
        ListBooksRequestBody:
            type: object
            properties:
                limit:
                    type: integer
                    description: Maximum number of books to return
                    default: 100
                    example: 62
                    format: int64
                    minimum: 1
                    maximum: 100
                offset:
                    type: integer
                    description: Field to paginate books
                    default: 0
                    example: 8136686838307245767
                    format: int64
                    minimum: 0
            example:
                limit: 39
                offset: 5524154035787004916
        Page:
            type: object
            properties:
                keywords:
                    type: array
                    items:
                        $ref: '#/components/schemas/Keyword'
                    description: Keywords of the page
                    example:
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                        - keyword: Unde recusandae saepe velit ullam omnis.
                title:
                    type: string
                    description: Title of the page
                    example: Nostrum perspiciatis quo commodi.
            example:
                keywords:
                    - keyword: Unde recusandae saepe velit ullam omnis.
                    - keyword: Unde recusandae saepe velit ullam omnis.
                    - keyword: Unde recusandae saepe velit ullam omnis.
                title: Id maiores est occaecati neque veritatis quae.
            required:
                - title
                - keywords
        UpdateBookRequestBody:
            type: object
            properties:
                author:
                    type: string
                    description: Author of the book
                    example: Porro aut voluptatum delectus ratione pariatur.
                language:
                    type: string
                    description: Language of the book
                    example: Quidem hic velit quia voluptatum.
                publisher:
                    type: string
                    description: Publisher of the book
                    example: Maxime ex similique unde.
                title:
                    type: string
                    description: Title of the book
                    example: Nisi ut totam doloremque repellendus voluptas tenetur.
            example:
                author: Itaque vero et neque earum expedita velit.
                language: Debitis quia incidunt illo tempora quia expedita.
                publisher: Magnam est.
                title: Atque quo vitae aspernatur.
            required:
                - title
                - author
                - language
                - publisher
tags:
    - name: epub_index_creator
