swagger: "2.0"
info:
    title: Epup Index Creator
    version: 0.0.1
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        get:
            tags:
                - epub_index_creator
            summary: ListBooks epub_index_creator
            operationId: epub_index_creator#ListBooks
            parameters:
                - name: ListBooksRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EpubIndexCreatorListBooksRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/BookResponseResponse'
            schemes:
                - http
        post:
            tags:
                - epub_index_creator
            summary: CreateBook epub_index_creator
            operationId: epub_index_creator#CreateBook
            parameters:
                - name: CreateBookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EpubIndexCreatorCreateBookRequestBody'
                    required:
                        - isbn
                        - title
                        - author
                        - language
                        - publisher
                        - pages
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EpubIndexCreatorCreateBookResponseBody'
                        required:
                            - isbn
                            - title
                            - author
                            - language
                            - publisher
                            - pages
            schemes:
                - http
    /books/{isbn}:
        get:
            tags:
                - epub_index_creator
            summary: FindBook epub_index_creator
            operationId: epub_index_creator#FindBook
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EpubIndexCreatorFindBookResponseBody'
                        required:
                            - isbn
                            - title
                            - author
                            - language
                            - publisher
                            - pages
            schemes:
                - http
        put:
            tags:
                - epub_index_creator
            summary: UpdateBook epub_index_creator
            operationId: epub_index_creator#UpdateBook
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  type: string
                - name: UpdateBookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EpubIndexCreatorUpdateBookRequestBody'
                    required:
                        - title
                        - author
                        - language
                        - publisher
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EpubIndexCreatorUpdateBookResponseBody'
                        required:
                            - isbn
                            - title
                            - author
                            - language
                            - publisher
                            - pages
            schemes:
                - http
        delete:
            tags:
                - epub_index_creator
            summary: DeleteBook epub_index_creator
            operationId: epub_index_creator#DeleteBook
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /books/{isbn}/pages:
        post:
            tags:
                - epub_index_creator
            summary: CreatePage epub_index_creator
            operationId: epub_index_creator#CreatePage
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  type: string
                - name: CreatePageRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EpubIndexCreatorCreatePageRequestBody'
                    required:
                        - page
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EpubIndexCreatorCreatePageResponseBody'
                        required:
                            - title
                            - keywords
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - epub_index_creator
            summary: Download ./gen/http/openapi.json
            operationId: epub_index_creator#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookResponseResponse:
        title: BookResponseResponse
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Alan A. A. Donovan, Brian W. Kernighan
            isbn:
                type: string
                example: 454-43000-0-9316-4
                pattern: ^[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]$
            language:
                type: string
                description: Language of the book
                example: English
            pages:
                type: array
                items:
                    $ref: '#/definitions/PageResponseResponse'
                description: Pages of the book
                example:
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
            publisher:
                type: string
                description: Publisher of the book
                example: Addison-Wesley
            title:
                type: string
                description: Title of the book
                example: The Go Programming Language
        example:
            author: Alan A. A. Donovan, Brian W. Kernighan
            isbn: 762-07-5-427-0
            language: English
            pages:
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
            publisher: Addison-Wesley
            title: The Go Programming Language
        required:
            - isbn
            - title
            - author
            - language
            - publisher
            - pages
    CreatePageRequestRequestBody:
        title: CreatePageRequestRequestBody
        type: object
        properties:
            keywords:
                type: array
                items:
                    type: string
                    example: Molestias aliquam sunt et numquam esse in.
                description: Keywords of the page
                example:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
            title:
                type: string
                description: Title of the page
                example: Introduction
        example:
            keywords:
                - Introduction
                - Chapter 1
                - Chapter 2
            title: Introduction
        required:
            - title
    EpubIndexCreatorCreateBookRequestBody:
        title: EpubIndexCreatorCreateBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Alan A. A. Donovan, Brian W. Kernighan
            isbn:
                type: string
                example: 500-4-1-29719-5
                pattern: ^[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]$
            language:
                type: string
                description: Language of the book
                example: English
            pages:
                type: array
                items:
                    $ref: '#/definitions/PageResponseRequestBody'
                description: Pages of the book
                example:
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
            publisher:
                type: string
                description: Publisher of the book
                example: Addison-Wesley
            title:
                type: string
                description: Title of the book
                example: The Go Programming Language
        example:
            author: Alan A. A. Donovan, Brian W. Kernighan
            isbn: 862-219-5-306-5
            language: English
            pages:
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
            publisher: Addison-Wesley
            title: The Go Programming Language
        required:
            - isbn
            - title
            - author
            - language
            - publisher
            - pages
    EpubIndexCreatorCreateBookResponseBody:
        title: EpubIndexCreatorCreateBookResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Alan A. A. Donovan, Brian W. Kernighan
            isbn:
                type: string
                example: 323-55639-8-008-2
                pattern: ^[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]$
            language:
                type: string
                description: Language of the book
                example: English
            pages:
                type: array
                items:
                    $ref: '#/definitions/PageResponseResponseBody'
                description: Pages of the book
                example:
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
            publisher:
                type: string
                description: Publisher of the book
                example: Addison-Wesley
            title:
                type: string
                description: Title of the book
                example: The Go Programming Language
        example:
            author: Alan A. A. Donovan, Brian W. Kernighan
            isbn: 303-7-955-4-5
            language: English
            pages:
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
            publisher: Addison-Wesley
            title: The Go Programming Language
        required:
            - isbn
            - title
            - author
            - language
            - publisher
            - pages
    EpubIndexCreatorCreatePageRequestBody:
        title: EpubIndexCreatorCreatePageRequestBody
        type: object
        properties:
            page:
                $ref: '#/definitions/CreatePageRequestRequestBody'
        example:
            page:
                keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                title: Introduction
        required:
            - page
    EpubIndexCreatorCreatePageResponseBody:
        title: EpubIndexCreatorCreatePageResponseBody
        type: object
        properties:
            keywords:
                type: array
                items:
                    type: string
                    example: Perferendis voluptatibus aliquam.
                description: Keywords of the page
                example:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
            title:
                type: string
                description: Title of the page
                example: Introduction
        example:
            keywords:
                - Introduction
                - Chapter 1
                - Chapter 2
            title: Introduction
        required:
            - title
            - keywords
    EpubIndexCreatorFindBookResponseBody:
        title: EpubIndexCreatorFindBookResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Alan A. A. Donovan, Brian W. Kernighan
            isbn:
                type: string
                example: 707-47-7-94-8
                pattern: ^[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]$
            language:
                type: string
                description: Language of the book
                example: English
            pages:
                type: array
                items:
                    $ref: '#/definitions/PageResponseResponseBody'
                description: Pages of the book
                example:
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
            publisher:
                type: string
                description: Publisher of the book
                example: Addison-Wesley
            title:
                type: string
                description: Title of the book
                example: The Go Programming Language
        example:
            author: Alan A. A. Donovan, Brian W. Kernighan
            isbn: 791-89118-5-26-3
            language: English
            pages:
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
            publisher: Addison-Wesley
            title: The Go Programming Language
        required:
            - isbn
            - title
            - author
            - language
            - publisher
            - pages
    EpubIndexCreatorListBooksRequestBody:
        title: EpubIndexCreatorListBooksRequestBody
        type: object
        properties:
            limit:
                type: integer
                description: Maximum number of books to return
                default: 100
                example: 36
                format: int64
                minimum: 1
                maximum: 100
            offset:
                type: integer
                description: Field to paginate books
                default: 0
                example: 7477527303227465786
                format: int64
                minimum: 0
        example:
            limit: 5
            offset: 8775834142765088175
    EpubIndexCreatorUpdateBookRequestBody:
        title: EpubIndexCreatorUpdateBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Ut veniam est aut occaecati odio corrupti.
            language:
                type: string
                description: Language of the book
                example: Commodi sint sint repellat sapiente porro nesciunt.
            publisher:
                type: string
                description: Publisher of the book
                example: Unde recusandae saepe velit ullam omnis.
            title:
                type: string
                description: Title of the book
                example: Aspernatur velit dolores aperiam adipisci qui.
        example:
            author: Laboriosam quae consequatur autem autem facilis aliquam.
            language: Dolor provident nulla corporis aspernatur.
            publisher: Dicta accusantium officiis totam omnis qui.
            title: Atque labore ad.
        required:
            - title
            - author
            - language
            - publisher
    EpubIndexCreatorUpdateBookResponseBody:
        title: EpubIndexCreatorUpdateBookResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Alan A. A. Donovan, Brian W. Kernighan
            isbn:
                type: string
                example: 811-2-17-8-2
                pattern: ^[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]$
            language:
                type: string
                description: Language of the book
                example: English
            pages:
                type: array
                items:
                    $ref: '#/definitions/PageResponseResponseBody'
                description: Pages of the book
                example:
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
                    - keywords:
                        - Introduction
                        - Chapter 1
                        - Chapter 2
                      title: Introduction
            publisher:
                type: string
                description: Publisher of the book
                example: Addison-Wesley
            title:
                type: string
                description: Title of the book
                example: The Go Programming Language
        example:
            author: Alan A. A. Donovan, Brian W. Kernighan
            isbn: 800-970-20-1-5
            language: English
            pages:
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
                - keywords:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
                  title: Introduction
            publisher: Addison-Wesley
            title: The Go Programming Language
        required:
            - isbn
            - title
            - author
            - language
            - publisher
            - pages
    PageResponseRequestBody:
        title: PageResponseRequestBody
        type: object
        properties:
            keywords:
                type: array
                items:
                    type: string
                    example: Sit velit quo.
                description: Keywords of the page
                example:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
            title:
                type: string
                description: Title of the page
                example: Introduction
        example:
            keywords:
                - Introduction
                - Chapter 1
                - Chapter 2
            title: Introduction
        required:
            - title
            - keywords
    PageResponseResponse:
        title: PageResponseResponse
        type: object
        properties:
            keywords:
                type: array
                items:
                    type: string
                    example: In omnis quaerat odit numquam ut repudiandae.
                description: Keywords of the page
                example:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
            title:
                type: string
                description: Title of the page
                example: Introduction
        example:
            keywords:
                - Introduction
                - Chapter 1
                - Chapter 2
            title: Introduction
        required:
            - title
            - keywords
    PageResponseResponseBody:
        title: PageResponseResponseBody
        type: object
        properties:
            keywords:
                type: array
                items:
                    type: string
                    example: Aut incidunt adipisci consectetur.
                description: Keywords of the page
                example:
                    - Introduction
                    - Chapter 1
                    - Chapter 2
            title:
                type: string
                description: Title of the page
                example: Introduction
        example:
            keywords:
                - Introduction
                - Chapter 1
                - Chapter 2
            title: Introduction
        required:
            - title
            - keywords
